server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/notifications_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: notifications
    password: notifications123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
